# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  authentication:
    image: badea741/authentication:v1
    build:
      context: .
      dockerfile: Authentication/Authentication.Entry/Dockerfile
    environment:
      - ConnectionStrings__Default=server=authenticationdb;Port=3308;database=LeqaaAuthentication;Uid=root;Pwd=2510203121;
      - Uri=http://localhost:5002
      - RabbitMQ__Host=rabbitmq
    ports:
      - 5002:5002
      - 5003:5003
    depends_on:
      - authenticationdb
      - rabbitmq
    volumes:
      - ./Authentication:/src/Authentication
    healthcheck:
      test: ["CMD","curl","-f","http://authenticationdb:3308"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: always


  authenticationdb:
    image: mysql/mysql-server:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=2510203121
      - MYSQL_DATABASE=LeqaaAuthentication
      - MYSQL_USER=root
      - MYSQL_PASSWORD=2510203121
      - MYSQL_TCP_PORT=3308
    volumes:
      - authenticationdbvolume:/var/lib/mysql
    ports:
      - 3308:3308

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "25672:25672"
      - "15671:15671"
      - "15672:15672"
    
  electronics_shop:
    image: badea741/takeideaandbuytommorow:v1
    build:
      context: .
      dockerfile: ElectronicsShop-service/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=shopdb;Port=3307;Database=BusinessLogicDb;Uid=root;Pwd=2510203121;
      - rabbitmq__Host=rabbitmq
    ports:
      - 5001:5001
    depends_on:
      - shopdb
      - rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping;curl --fail http://shopdb:3307
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: always

  shopdb:
    image: mysql/mysql-server:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=2510203121
      - MYSQL_DATABASE=BusinessLogicDb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=2510203121
      - MYSQL_TCP_PORT=3307

    volumes:
      - businessdbvolume:/var/lib/mysql2
    ports:
      - 3307:3307
    restart: always

volumes:
  businessdbvolume:
  authenticationdbvolume:

